---
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  attributes:
    marketplace_image:
      package_install_channel: <%= ENV['CHANNEL'] || 'stable' %>

platforms:
  - name: publish
    driver_plugin: vagrant
    driver_config:
      box: bento/ubuntu-14.04
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: azure_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          automate:
            enabled: true
  - name: gce_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          automate:
            enabled: true
  - name: aws_public_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
  - name: aws_public_byol_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public_byol:
            automate:
              enabled: true
  - name: aws_ic_automate # doesn't do anything; see attributes/aws.rb
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            automate:
              enabled: true
  - name: aws_ic_byol_automate # doesn't do anything; see attributes/aws.rb
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic_byol:
            automate:
              enabled: true
  - name: all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
          public_byol:
            automate:
              enabled: true
          ic:      # doesn't do antyhing; see attributes/aws.rb
            automate:
              enabled: true
          ic_byol: # doesn't do anything; see attributes/aws.rb
            automate:
              enabled: true
        azure:
          automate:
            enabled: true
        gce:
          automate:
            enabled: true
