---
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  attributes:
    marketplace_image:
      package_install_channel: <%= ENV['CHANNEL'] || 'stable' %>

platforms:
  - name: publish
    driver_plugin: vagrant
    driver_config:
      box: bento/ubuntu-14.04
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: azure_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          compliance:
            enabled: true
  - name: azure_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          automate:
            enabled: true
  - name: azure_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          automate:
            enabled: true
          compliance:
            enabled: true

  - name: gce_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          compliance:
            enabled: true
  - name: gce_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          automate:
            enabled: true
  - name: gce_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          automate:
            enabled: true
          compliance:
            enabled: true

  - name: vmware_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        vmware:
          compliance:
            enabled: true
  - name: vmware_automate
    run_list: "marketplace_image::default"
    attributes:
      vmware:
        packer_ssh_password: <%= ENV['PACKER_SSH_PASSWORD'] %>
        esx_host: <%= ENV['ESX_HOST'] %>
        esx_password: <%= ENV['ESX_PASSWORD'] %>
      packman:
        version: '1.1.0'
      marketplace_image:
        vmware:
          automate:
            enabled: true
  - name: vmware_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        vmware:
          automate:
            enabled: true
          compliance:
            enabled: true

  - name: aws_public_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
  - name: aws_public_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            compliance:
              enabled: true
  - name: aws_public_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
            compliance:
              enabled: true
  - name: aws_ic_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            compliance:
              enabled: true
  - name: aws_ic_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            automate:
              enabled: true
  - name: aws_ic_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            automate:
              enabled: true
            compliance:
              enabled: true
  - name: aws_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
            compliance:
              enabled: true
          ic:
            automate:
              enabled: true
            compliance:
              enabled: true

  - name: all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
            compliance:
              enabled: true
          ic:
            automate:
              enabled: true
            compliance:
              enabled: true
        azure:
          automate:
            enabled: true
          compliance:
            enabled: true
        gce:
          automate:
            enabled: true
          compliance:
            enabled: true
        vmware:
          automate:
            enabled: true
          compliance:
            enabled: true
