---
driver:
  name: vagrant
  box: bento/ubuntu-14.04
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  product_name: chefdk
  channel: current
  attributes:
    marketplace_image:
      package_install_channel: <%= ENV['CHANNEL'] || 'stable' %>

platforms:
  - name: publish
suites:
  - name: azure_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          automate:
            enabled: true
  - name: gce_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          automate:
            enabled: true
  - name: aws_public_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
  - name: aws_public_byol_automate
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public_byol:
            automate:
              enabled: true
  - name: aws_ic_automate # doesn't do anything; see attributes/aws.rb
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            automate:
              enabled: true
  - name: aws_ic_byol_automate # doesn't do anything; see attributes/aws.rb
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic_byol:
            automate:
              enabled: true
  - name: all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            automate:
              enabled: true
          public_byol:
            automate:
              enabled: true
          ic:      # doesn't do antyhing; see attributes/aws.rb
            automate:
              enabled: true
          ic_byol: # doesn't do anything; see attributes/aws.rb
            automate:
              enabled: true
        azure:
          automate:
            enabled: true
        gce:
          automate:
            enabled: true
