---
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: publish
    driver_plugin: vagrant
    driver_config:
      box: bento/ubuntu-14.04
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: azure_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          compliance:
            enabled: true
  - name: azure_aio
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          aio:
            enabled: true
  - name: azure_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        azure:
          aio:
            enabled: true
          compliance:
            enabled: true
  - name: gce_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          compliance:
            enabled: true
  - name: gce_aio
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          aio:
            enabled: true
  - name: gce_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        gce:
          aio:
            enabled: true
          compliance:
            enabled: true

  - name: aws_public_aio
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              enabled: true
  - name: aws_public_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            compliance:
              enabled: true
  - name: aws_public_flexible_aio
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              fcp_enabled: true
  - name: aws_public_flexible_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            compliance:
              fcp_enabled: true
  - name: aws_public_flexible_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              fcp_enabled: true
            compliance:
              fcp_enabled: true
  - name: aws_public_fixed_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              enabled: true
            compliance:
              enabled: true
  - name: aws_public_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              enabled: true
              fcp_enabled: true
            compliance:
              enabled: true
              fcp_enabled: true
  - name: aws_ic_compliance
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            compliance:
              enabled: true
  - name: aws_ic_aio
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            aio:
              enabled: true
  - name: aws_ic_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          ic:
            aio:
              enabled: true
            compliance:
              enabled: true
  - name: aws_all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              enabled: true
              fcp_enabled: true
            compliance:
              enabled: true
              fcp_enabled: true
          ic:
            aio:
              enabled: true
            compliance:
              enabled: true
  - name: all
    run_list: "marketplace_image::default"
    attributes:
      marketplace_image:
        aws:
          public:
            aio:
              enabled: true
              fcp_enabled: true
            compliance:
              enabled: true
              fcp_enabled: true
          ic:
            aio:
              enabled: true
            compliance:
              enabled: true
        azure:
          aio:
            enabled: true
          compliance:
            enabled: true
        gce:
          aio:
            enabled: true
          compliance:
            enabled: true
