Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/AbcSize:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/CyclomaticComplexity:
  Enabled: false
Style/PerceivedComplexity:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Documentation:
  Enabled: false
