Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Style/GuardClause:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Documentation:
  Enabled: false
